#Data Preprocessing

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [ ]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target


In [ ]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [ ]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
y

array([5, 5, 5, ..., 6, 5, 6])

#Splitting of data into test and train 

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
y_train

array([6, 5, 6, ..., 6, 5, 5])

In [ ]:
y_test

array([3, 6, 6, 5, 5, 5, 6, 5, 5, 7, 5, 6, 6, 5, 6, 6, 5, 7, 5, 6, 5, 5,
       5, 6, 5, 5, 6, 5, 5, 7, 7, 5, 6, 6, 5, 6, 6, 5, 5, 4, 5, 6, 5, 5,
       3, 6, 5, 5, 5, 4, 5, 6, 4, 5, 6, 6, 5, 6, 7, 5, 6, 7, 5, 5, 6, 6,
       6, 6, 5, 7, 6, 6, 5, 4, 6, 5, 5, 6, 5, 6, 5, 6, 5, 7, 6, 6, 5, 5,
       5, 6, 5, 5, 5, 7, 7, 6, 7, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 5,
       7, 5, 5, 6, 5, 6, 7, 7, 5, 5, 8, 6, 6, 6, 5, 5, 6, 6, 7, 5, 7, 5,
       5, 6, 4, 7, 5, 6, 6, 5, 6, 5, 6, 5, 5, 6, 7, 5, 5, 7, 6, 6, 8, 5,
       6, 5, 6, 6, 7, 6, 5, 5, 6, 6, 5, 6, 5, 5, 5, 6, 7, 5, 5, 6, 5, 7,
       5, 6, 5, 5, 6, 5, 6, 7, 5, 6, 5, 6, 5, 5, 8, 5, 5, 6, 5, 6, 7, 5,
       6, 5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 5, 4, 7, 5, 6, 7, 6, 7, 6, 6, 7,
       6, 6, 5, 6, 6, 7, 6, 5, 6, 8, 6, 5, 6, 6, 6, 6, 6, 5, 3, 3, 6, 7,
       5, 5, 7, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 4, 5, 5, 5, 5,
       5, 6, 6, 6, 5, 5, 7, 6, 6, 5, 6, 5, 5, 6, 4, 5, 5, 5, 7, 7, 6, 4,
       5, 5, 6, 6, 6, 4, 7, 6, 5, 6, 5, 5, 6, 5, 6,

#Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ptrain = y_train.reshape(len(y_train), 1)
ptest = y_test.reshape(len(y_test), 1)

In [ ]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [ ]:
xp_train = x_sc.fit_transform(x_train)
yp_train = y_sc.fit_transform(ptrain)

In [ ]:
xp_test = x_sc.transform(x_test)
yp_test = y_sc.transform(ptest)

In [ ]:
len(xp_train)

1279

In [ ]:
xp_train

array([[ 1.90302515, -1.62367409,  1.54401494, ..., -1.11176211,
         0.25802721, -0.49658064],
       [ 1.439169  , -1.45746441,  0.92266825, ..., -1.17731666,
        -0.69217413, -0.78362191],
       [ 0.85934882, -0.07238373, -0.4235829 , ..., -0.52177116,
        -0.4546238 ,  0.07750189],
       ...,
       [-0.24230953,  0.12152756, -1.09670848, ...,  0.33043799,
         0.07986446,  0.26886273],
       [-0.24230953, -0.95883536, -0.32002512, ..., -0.25955296,
        -0.4546238 , -0.87930233],
       [-0.35827357,  2.42076149, -0.37180401, ...,  0.33043799,
        -1.28604997,  0.46022358]])

In [ ]:
len(xp_test)

320

In [ ]:
xp_test

array([[ 1.90302515,  0.31543886,  2.01002495, ..., -0.39066206,
        -0.51401138, -1.35770444],
       [-1.1120398 ,  1.89443083, -1.25204515, ...,  1.96930173,
        -0.98911205,  2.18247118],
       [-0.64818366,  0.03842272, -0.68247735, ...,  0.26488344,
        -0.27646104,  1.60838864],
       ...,
       [ 2.65679138, -0.12778696,  1.44045716, ..., -1.43953486,
         0.13925204,  0.46022358],
       [-0.18432751, -0.12778696,  0.61199491, ...,  0.78931984,
        -0.21707346,  0.26886273],
       [-0.06836347,  2.64237439, -0.94137181, ...,  0.06821979,
        -0.63278655, -1.35770444]])

In [ ]:
yp_train

array([[ 0.44867028],
       [-0.80154603],
       [ 0.44867028],
       ...,
       [ 0.44867028],
       [-0.80154603],
       [-0.80154603]])

#Train on different algorithms

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [ ]:
x_pol = PolynomialFeatures(degree=5)
x_pol = x_pol.fit_transform(xp_train)

In [ ]:
temp = PolynomialFeatures(degree=5)
temp = temp.fit_transform(xp_test)

In [ ]:
r_reg.fit(xp_train, yp_train)
l_reg.fit(xp_train, yp_train)
d_reg.fit(xp_train, yp_train)
s_reg.fit(xp_train, yp_train)
p_reg.fit(x_pol, yp_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
r_pred = r_reg.predict(xp_test)
l_pred = l_reg.predict(xp_test)
d_pred = d_reg.predict(xp_test)
s_pred = s_reg.predict(xp_test)
p_pred = p_reg.predict(temp)

#Result

In [ ]:

from sklearn.metrics import r2_score

In [ ]:
r = r2_score(yp_test, r_pred)
l = r2_score(yp_test, l_pred)
d = r2_score(yp_test, d_pred)
s = r2_score(yp_test, s_pred)
p = r2_score(yp_test, p_pred)

In [ ]:
print(r, l, d, s, p)

0.4629014261569191 0.34537535718694123 0.056864689695631965 0.3404175181257688 -1430.037071221998


#Conclusion

###We have solved it using regression techique



*   As we have observed RandomForest is giving more efficiency 
    than any other algorithmic techniques
    ,so we can conclude that RandomForest is the best algorithmic       technique for this data set.
